server:
  port: 8088

spring:
  redis:
    port: 6379
    password: zhongtai@_Ra1i
    host: 127.0.0.1
    jedis:
      pool:
        max-idle: 6     #最大空闲数
        max-active: 10  #最大连接数
        min-idle: 2     #最小空闲数
    timeout: 2000   #连接超时
  datasource:
    url: jdbc:mysql://localhost:3306/cndata?useunicode=true&characterEncoding=utf8
    username: root
    password: meiyisi123
    driver-class-name: com.mysql.jdbc.Driver

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.bootjedis.pojo
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


