package com.example.springboot.mapper;

import com.example.springboot.pojo.ColumnDetailHis;
import java.util.List;

public interface ColumnDetailHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_detail_his
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_detail_his
     *
     * @mbggenerated
     */
    int insert(ColumnDetailHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_detail_his
     *
     * @mbggenerated
     */
    ColumnDetailHis selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_detail_his
     *
     * @mbggenerated
     */
    List<ColumnDetailHis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_detail_his
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ColumnDetailHis record);
}