package com.example.springboot.mapper;

import com.example.springboot.pojo.ColumnDetail;
import java.util.List;

public interface ColumnDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_detail
     *
     * @mbggenerated
     */
    int insert(ColumnDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_detail
     *
     * @mbggenerated
     */
    ColumnDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_detail
     *
     * @mbggenerated
     */
    List<ColumnDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ColumnDetail record);
}